---
language: node_js
node_js:
  - "10.14.2"

sudo: false

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
    - COVERAGE=true
    - MIRAGE_LOGGING=false
    - PERCY_ENABLE=0

addons:
  firefox: latest

before_install:
  - npm -v

install:
  - npm install

script:
  - npm run lint:hbs
  - npm run lint:js
  - npm test
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  provider: script
  script: .travis/deploy-sandbox.sh
  skip_cleanup: true
  on:
    repo: backspace/prison-rideshare-ui
    branch: primary

after_success:
  - "test $TRAVIS_PULL_REQUEST && test $TRAVIS_PULL_REQUEST != 'false' && $TRAVIS_SECURE_ENV_VARS == 'true' && .travis/deploy-pull-request.sh"
