---
language: node_js
node_js:
  - "9.2.0"

sudo: false

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
    - COVERAGE=true
    - MIRAGE_LOGGING=false

addons:
  firefox: latest

before_install:
  - npm config set spin false
  - npm -v

install:
  - npm install

script:
  - npm test
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose

deploy:
  provider: script
  script: .travis/deploy-sandbox.sh
  on:
    repo: backspace/prison-rideshare-ui
    branch: primary
